### ISSUE TITLE
（十四）「关系」表 7：中间表 图片上的字段写错了

### ISSUE THREAD

**Issue by mjopenglsdl** [guobinhit/mysql-tutorial#6]
最下面一张表7，2个字段都是**STU_ID**
[https://github.com/guobinhit/mysql-tutorial/blob/master/articles/relation.md](https://github.com/guobinhit/mysql-tutorial/blob/master/articles/relation.md)

**Comment by guobinhit** [comment]
确实写错了，感谢指正。
